zeebe:
  client:
    worker:
      defaultName: script-worker
      defaultType: script
      threads: 3

    job.timeout: 10000
    broker.contactPoint: zeebe:26500
    security.plaintext: true

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.script: DEBUG
